trigger: none

variables:
  acrServiceConnection: 'sourish-acr-connection'
  acrName: 'sourishACRBasuDemo'
  aksServiceConnection: 'aks-connection'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      name: 'selfHostedPool'
    steps:

    - task: DockerInstaller@0
      displayName: 'Docker Installer'
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: KubectlInstaller@0
      displayName: 'Kubectl Installer'
      inputs:
        kubectlVersion: 'latest'

    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: 'backend'
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        tags: '$(Build.BuildId)'

    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: 'frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: '$(Build.BuildId)'

- stage: Deploy
  jobs:
  - job: DeployToAKS
    pool:
      name: 'selfHostedPool'
    steps:
    - task: KubernetesManifest@0
      displayName: 'Deploy to AKS'
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: '$(aksServiceConnection)'
        manifests: 'kubernetes/deployment.yaml'
