trigger: none

variables:
  serviceConnection: 'azure-service-connection'
  resourceGroupName: 'terraform-rg'
  storageAccountName: 'terraformsasourishbasu'
  containerName: 'tfstate'
  stateFileName: 'terraform.tfstate'

stages:
- stage: Terraform
  jobs:
  - job: Deploy
    pool:
      name: 'selfHostedPool'

    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init
        terraform plan
      displayName: 'Terraform Init'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: '$(serviceConnection)'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: '$(serviceConnection)'
        commandOptions: '-auto-approve'
