trigger: none

variables:
  serviceConnection: 'azure-service-connection'
  resource_group_name: 'terraform-rg'
  storage_account_name: 'terraformsasourishbasu'
  container_name: 'tfstate'
  key: 'terraform.tfstate'

stages:
- stage: Terraform
  jobs:
  - job: Deploy
    pool:
      name: 'selfHostedPool'

    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init -backend-config="backend.tfvars"
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      displayName: 'Terraform Init'

    - script: |
        terraform plan 
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -auto-approve
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      displayName: 'Terraform Apply'

