trigger: none

stages:
- stage: Terraform
  jobs:
  - job: Deploy
    pool:
      name: 'selfHostedPool'

    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init 
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      displayName: 'Terraform Init'

    - script: |
        terraform plan 
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -auto-approve
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      displayName: 'Terraform Apply'

