trigger: none

variables:
  serviceConnection: 'azure-service-connection'
  ARM_CLIENT_ID: '$(servicePrincipalId)'
  ARM_CLIENT_SECRET: '$(servicePrincipalKey)'
  ARM_SUBSCRIPTION_ID: '$(subscriptionId)'
  ARM_TENANT_ID: '$(tenantId)'

stages:
- stage: Terraform
  jobs:
  - job: Deploy
    pool:
      name: 'selfHostedPool'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmStorageAccountName: 'terraformsasourishbasu'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: '$(serviceConnection)'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: '$(serviceConnection)'
        commandOptions: '-auto-approve'